### ISSUE TITLE
ignorePattern is deprecated

### ISSUE THREAD

**Issue by PXMYH** [pirixtech/Jarvis#14]
```ERROR
18:15
jest-haste-map: the `ignorePattern` options as a function is being deprecated. Provide a RegExp instead. See https://github.com/facebook/jest/pull/4063.
ERROR
18:15
jest-haste-map: Watchman crawl failed. Retrying once with node crawler.
  Usually this happens when watchman isn't running. Create an empty `.watchmanconfig` file in your project's root folder or initialize a git or hg repository in your project.
  TypeError: ignorePattern is not a function
ERROR
18:15
/Volumes/workplace/Jarvis/client/node_modules/jest-haste-map/build/index.js:1320
        : ignorePattern && ignorePattern(filePath);
                           ^
TypeError: ignorePattern is not a function
    at HasteMap._ignore (/Volumes/workplace/Jarvis/client/node_modules/jest-haste-map/build/index.js:1320:28)
    at /Volumes/workplace/Jarvis/client/node_modules/jest-haste-map/build/crawlers/node.js:203:21
    at Array.filter (<anonymous>)
    at Socket.<anonymous> (/Volumes/workplace/Jarvis/client/node_modules/jest-haste-map/build/crawlers/node.js:203:8)
    at Socket.emit (events.js:326:22)
    at Pipe.<anonymous> (net.js:672:12)
```

**Comment by PXMYH** [comment]
Fixed
